version: '3'
services:
  api:
    image: my-api
    build: ./api
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/site-all.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
